CREATE TABLE run (
  id CHAR(36) NOT NULL PRIMARY KEY,
  user_id CHAR(36) NOT NULL,
  run_time VARCHAR(255) NOT NULL,
  run_kilometers DECIMAL(10, 2) NOT NULL,
  run_city VARCHAR(255) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  created_by CHAR(36) NOT NULL,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL,
  updated_by CHAR(36) NOT NULL,
  deleted_at TIMESTAMP NULL DEFAULT NULL,
  deleted_by CHAR(36) NULL DEFAULT NULL
);
